id: P004568
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:42:07.488983
source_metadata:
  id: bdr:W3CN1482
  title: སྤྱོད་འཇུག་གི་འགྲེལ་པ་ངེས་ལེགས་མཛོད།
  author: ''
  volumes:
    075f52c377f04afaa325415ad3b37aa6:
      image_group_id: I3CN1538
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
