id: I40ED4810
legacy_id: P004568
ocr_import_info:
  bdrc_scan_id: W3CN1482
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T21:06:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-18T07:02:02.589886+00:00'
last_modified: 2022-08-18 12:32:20.555741
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1482
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1482
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་གི་འགྲེལ་པ་ངེས་ལེགས་མཛོད།
  author: སྨུག་སངས་ཀརྨ་ཚེ་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.5521146171231213
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I3CN1538:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1538
      total_pages: 292
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1538.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5521146171231213
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
